server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#spring:
  redis:
    host: 192.168.136.128
    port: 6379
    database: 0
    password:  #默认为空
    timeout: 1800000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    pool:
      max-active: 20  #最大连接数，负值表示没有限制，默认8
      max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
      max-idle: 8     #最大空闲连接，默认8
      min-idle: 0     #最小空闲连接，默认0

#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: LTAI5tNWvjW7SycCZSZaTXGY
    key-secret: MNFvVGBZ5x1Qx7Ae6lyRZvkkGFKiLw
    template-code: SMS_154950909
    sign-name: 阿里云短信测试

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel:
    enabled: true

logging:
  level:
    com.atguigu.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口
